---
title: "Assignment - Naive Bayes DIY, reviewed version"
author:
  - Danny Bannink (Reviewer)
  - Teun Vlassak (Author)
date: 
```{r}
format(Sys.time(), '%d %B, %Y')
```
---

```{r}
library(tidyverse)
library(class)
library(wordcloud)
library(tm)
library(caret)
library(e1071)
```

## Data Understanding

```{r}
rawdf <- (NB_fakenews)
head(rawdf) # In the sabotaged version, Teun made a mistake were the 'head-function' would list out only 1 column of the datatable instead of all.
class(rawdf)
```


```{r}
rawdf$label <- factor(rawdf$label, levels = c("0", "1"), labels = c("Real", "Fake")) %>% factor %>% relevel("Fake")
class(rawdf$label)
```

```{r}
Real <- rawdf %>% filter(label == "Real")
Fake <- rawdf %>% filter(label == "Fake")

wordcloud(Real$text, max.words = 20, scale = c(4, 0.8), colors= c("indianred1","indianred2","indianred3","indianred"))
wordcloud(Fake$text, max.words = 20, scale = c(4, 0.8), colors= c("lightsteelblue1","lightsteelblue2","lightsteelblue3","lightsteelblue"))
```


##Preparation
```{r}
rawCorpus <- Corpus(VectorSource(rawdf$text))
inspect(rawCorpus[1:5]) # The ratio of the sabotaged version was '1:3' instead of the to be used '1:5'. 
```

```{r}
cleanCorpus <- rawCorpus %>% tm_map(tolower) %>% tm_map(removeNumbers)
cleanCorpus <- cleanCorpus %>% tm_map(tolower) %>% tm_map(removeWords, stopwords()) %>% tm_map(removePunctuation)
cleanCorpus <- cleanCorpus %>% tm_map(stripWhitespace) 
```

```{r}
tibble(Raw = rawCorpus$content[1:5], Clean = cleanCorpus$content[1:5])
cleanDTM <- cleanCorpus %>% DocumentTermMatrix
inspect(cleanDTM)
```

```{r}
set.seed(1234)
trainIndex <- createDataPartition(rawdf$label, p = .75, 
                                  list = FALSE, 
                                  times = 1)
head(trainIndex)
```

```{r}
# In the original sabotaged version, Teun put a '2' within the brackets of line 72, 73, 80 and 81. This added no value and caused the code to not work properly. I deleted this '2's'. 
trainDF <- rawdf[trainIndex, ]
testDF <- rawdf[-trainIndex, ]


trainCorpus <- cleanCorpus[trainIndex]
testCorpus <- cleanCorpus[-trainIndex]


trainDTM <- cleanDTM[trainIndex, ]
testDTM <- cleanDTM[-trainIndex, ]
```

```{r}
freqWords <- trainDTM %>% findFreqTerms(300) # In th sabotaged version, Teun put in the mistake in which the value of the 'findFreqTerms' function was much lower than the shown '300'. 
trainDTM <-  DocumentTermMatrix(trainCorpus, list(dictionary = freqWords))
testDTM <-  DocumentTermMatrix(testCorpus, list(dictionary = freqWords))
```

```{r}
convert_counts <- function(x) {
  x <- ifelse(x > 0, 1, 0) %>% factor(levels = c(0,1), labels = c("No", "Yes"))
}

nColsDTM <- dim(trainDTM)[2]
trainDTM <- apply(trainDTM, MARGIN = 2, convert_counts)
testDTM <- apply(testDTM, MARGIN = 2, convert_counts)

head(trainDTM[,1:10])
```

##Modeling and Evaluation
```{r}
nbayesModel <-  naiveBayes(trainDTM, trainDF$label, laplace = 1)
```

```{r}
predVec <- predict(nbayesModel, testDTM)
confusionMatrix(predVec, testDF$label, positive = "Fake", dnn = c("Prediction", "True"))
```


